# Creator: djuelg @ https://github.com/djuelg
# Run via: hugo server --theme=Shapez-Theme --buildDrafts --bind="0.0.0.0"

baseurl = "https://veruskasantos.github.io/VisualizacaoAcudeBoqueirao/"
title = "Açude Epitácio Pessoa"
theme = "Shapez-Theme"
publishDir = "docs"
copyright = "Copyright (c) 2017, Veruska Santos"
[author]
    name = ""
    
languageCode = "en-US"
MetaDataFormat = "toml"
PaginatePath = "page"
googleAnalytics = ""

[params]
    
    description = "This is the sites description, which will be found in the meta tags."

    # Homepage Start-Screen, variables can be left empty, links dont start with /
    title_l1 = "Açude Epitácio Pessoa"
    title_l2 = "Boqueirão"
    subtitle_l1 = "Veja abaixo algumas análises feitas sobre"
    subtitle_l2 = "o volume deste tão importante açude."
    subtitle_l3 = "Dados atualizados pela AESA."
    subtitle_link = ""

    start_screen_image_quality = "auto"

    # Enter links for the buttons (button one has the house sign), shouldn't be left empty
    button_1 = ""
    button_2 = "post/terceiro-post/"
    button_3 = "about/"

    paginate = 2
    keywords = "hugo, blog, Shapez, SVG, design"